[project]
name = "burn-mesh"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.nft-core]
path = "contracts/nft-core.clar"
depends_on = []

[contracts.nft-licensing]
path = "contracts/nft-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
